services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: revoicechat_client
    ports:
      - "${WEB_CLIENT_PORT:-5000}:5000"
    volumes:
      - ./www:/usr/share/nginx/html
    restart: unless-stopped
networks:
  default:
    name: app-network